# Generated by Django 5.1.1 on 2024-10-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=360, null=True)),
                ('genre', models.CharField(choices=[('New', 'New on Streamada'), ('Sport', 'Sport'), ('Explore', 'Explore'), ('Western', 'Western'), ('Crime', 'Crime'), ('Abstract', 'Abstract')], max_length=100)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('add_to_new_video_feed', models.BooleanField(default=False)),
            ],
        ),
    ]
