# Generated by Django 5.1.1 on 2024-10-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('new_on_streamada', 'New on Streamada'), ('sport', 'Sport'), ('explore', 'Explore'), ('western', 'Western'), ('crime', 'Crime'), ('abstract', 'Abstract')], max_length=100),
        ),
    ]
