# Generated by Django 5.1.1 on 2024-10-02 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamada', '0002_alter_video_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
    ]
