# Generated by Django 5.1.1 on 2024-10-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamada', '0004_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('New', 'New on Streamada'), ('Sport', 'Sport'), ('Explore', 'Explore'), ('Western', 'Western'), ('Crime', 'Crime'), ('Abstract', 'Abstract')], max_length=100),
        ),
    ]
