# Generated by Django 5.1.1 on 2024-10-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamada', '0005_alter_video_description_alter_video_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=480, null=True),
        ),
    ]
