# Generated by Django 5.1.1 on 2024-10-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamada', '0007_video_add_to_new_video_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='add_to_new_video_feed',
            field=models.BooleanField(default=False),
        ),
    ]
