# Generated by Django 5.1.1 on 2024-10-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamada', '0008_alter_video_add_to_new_video_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=360, null=True),
        ),
    ]
